//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Input/VRControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @VRControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @VRControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""VRControls"",
    ""maps"": [
        {
            ""name"": ""VRPlayer"",
            ""id"": ""c485fa79-512c-4b2e-8eaf-205066e8c0e4"",
            ""actions"": [
                {
                    ""name"": ""Teleport"",
                    ""type"": ""Button"",
                    ""id"": ""f5225d79-4421-43ef-a2d5-9f9801550d96"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""c3234ed7-5185-42e1-afde-743fe78529f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PickupLeft"",
                    ""type"": ""Button"",
                    ""id"": ""f687e5c3-ec32-4a71-9ee1-3bfed182862a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PickupRight"",
                    ""type"": ""Button"",
                    ""id"": ""9aca2f8f-cec3-46e8-b9dc-8295feeab979"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0892fbad-f6f6-4719-9513-60cd567de5c4"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Teleport"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f5bf36de-5e83-4b00-b86f-a77f0181a156"",
                    ""path"": ""<XRInputV1::HP::HPReverbG2ControllerOpenXR>{LeftHand}/thumbstickclicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Teleport"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ca05b26-e272-4818-bcc2-c4cc52149b64"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf6d9f0d-b4c4-4ef6-a332-51ac7c0e121b"",
                    ""path"": ""<HPMixedRealityController>{RightHand}/menu"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""37601135-4a70-4c71-b196-c96fe1f22c57"",
                    ""path"": ""<HPMixedRealityController>{LeftHand}/menu"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9effb11e-9dd0-4220-824e-d7000db6dfba"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PickupLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f0b8fe9a-46a2-4e69-9ed5-5ef38dca6818"",
                    ""path"": ""<XRInputV1::HP::HPReverbG2ControllerOpenXR>{LeftHand}/triggerpressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PickupLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f4ac746-4094-48a5-9045-d333f2c19a11"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PickupRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e00e1450-4a7a-4c00-b70b-e1394747608f"",
                    ""path"": ""<XRInputV1::HP::HPReverbG2ControllerOpenXR>{RightHand}/triggerpressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PickupRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // VRPlayer
        m_VRPlayer = asset.FindActionMap("VRPlayer", throwIfNotFound: true);
        m_VRPlayer_Teleport = m_VRPlayer.FindAction("Teleport", throwIfNotFound: true);
        m_VRPlayer_Menu = m_VRPlayer.FindAction("Menu", throwIfNotFound: true);
        m_VRPlayer_PickupLeft = m_VRPlayer.FindAction("PickupLeft", throwIfNotFound: true);
        m_VRPlayer_PickupRight = m_VRPlayer.FindAction("PickupRight", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // VRPlayer
    private readonly InputActionMap m_VRPlayer;
    private IVRPlayerActions m_VRPlayerActionsCallbackInterface;
    private readonly InputAction m_VRPlayer_Teleport;
    private readonly InputAction m_VRPlayer_Menu;
    private readonly InputAction m_VRPlayer_PickupLeft;
    private readonly InputAction m_VRPlayer_PickupRight;
    public struct VRPlayerActions
    {
        private @VRControls m_Wrapper;
        public VRPlayerActions(@VRControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Teleport => m_Wrapper.m_VRPlayer_Teleport;
        public InputAction @Menu => m_Wrapper.m_VRPlayer_Menu;
        public InputAction @PickupLeft => m_Wrapper.m_VRPlayer_PickupLeft;
        public InputAction @PickupRight => m_Wrapper.m_VRPlayer_PickupRight;
        public InputActionMap Get() { return m_Wrapper.m_VRPlayer; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(VRPlayerActions set) { return set.Get(); }
        public void SetCallbacks(IVRPlayerActions instance)
        {
            if (m_Wrapper.m_VRPlayerActionsCallbackInterface != null)
            {
                @Teleport.started -= m_Wrapper.m_VRPlayerActionsCallbackInterface.OnTeleport;
                @Teleport.performed -= m_Wrapper.m_VRPlayerActionsCallbackInterface.OnTeleport;
                @Teleport.canceled -= m_Wrapper.m_VRPlayerActionsCallbackInterface.OnTeleport;
                @Menu.started -= m_Wrapper.m_VRPlayerActionsCallbackInterface.OnMenu;
                @Menu.performed -= m_Wrapper.m_VRPlayerActionsCallbackInterface.OnMenu;
                @Menu.canceled -= m_Wrapper.m_VRPlayerActionsCallbackInterface.OnMenu;
                @PickupLeft.started -= m_Wrapper.m_VRPlayerActionsCallbackInterface.OnPickupLeft;
                @PickupLeft.performed -= m_Wrapper.m_VRPlayerActionsCallbackInterface.OnPickupLeft;
                @PickupLeft.canceled -= m_Wrapper.m_VRPlayerActionsCallbackInterface.OnPickupLeft;
                @PickupRight.started -= m_Wrapper.m_VRPlayerActionsCallbackInterface.OnPickupRight;
                @PickupRight.performed -= m_Wrapper.m_VRPlayerActionsCallbackInterface.OnPickupRight;
                @PickupRight.canceled -= m_Wrapper.m_VRPlayerActionsCallbackInterface.OnPickupRight;
            }
            m_Wrapper.m_VRPlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Teleport.started += instance.OnTeleport;
                @Teleport.performed += instance.OnTeleport;
                @Teleport.canceled += instance.OnTeleport;
                @Menu.started += instance.OnMenu;
                @Menu.performed += instance.OnMenu;
                @Menu.canceled += instance.OnMenu;
                @PickupLeft.started += instance.OnPickupLeft;
                @PickupLeft.performed += instance.OnPickupLeft;
                @PickupLeft.canceled += instance.OnPickupLeft;
                @PickupRight.started += instance.OnPickupRight;
                @PickupRight.performed += instance.OnPickupRight;
                @PickupRight.canceled += instance.OnPickupRight;
            }
        }
    }
    public VRPlayerActions @VRPlayer => new VRPlayerActions(this);
    public interface IVRPlayerActions
    {
        void OnTeleport(InputAction.CallbackContext context);
        void OnMenu(InputAction.CallbackContext context);
        void OnPickupLeft(InputAction.CallbackContext context);
        void OnPickupRight(InputAction.CallbackContext context);
    }
}
